# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {BD 41-968}  -string {{xillybus_S_AXI}}  -new_severity {INFO} 
set_msg_config  -ruleid {2}  -id {BD 41-967}  -string {{xillybus_ip_0/xillybus_M_AXI}}  -new_severity {INFO} 
set_msg_config  -ruleid {3}  -id {BD 41-967}  -string {{xillybus_ip_0/xillybus_S_AXI}}  -new_severity {INFO} 
set_msg_config  -ruleid {4}  -id {BD 41-678}  -string {{xillybus_S_AXI/Reg}}  -new_severity {INFO} 
set_msg_config  -ruleid {5}  -id {BD 41-1356}  -string {{xillybus_S_AXI/Reg}}  -new_severity {INFO} 
set_msg_config  -ruleid {7}  -id {BD 41-759}  -string {{xlconcat_0/In}}  -new_severity {INFO} 
set_msg_config  -ruleid {8}  -id {Netlist 29-160}  -string {{vivado_system_processing_system7}}  -new_severity {INFO} 
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/vytas/INF4/Verilog/inf4_proj_dev/inf4_proj_dev.cache/wt [current_project]
set_property parent.project_path /home/vytas/INF4/Verilog/inf4_proj_dev/inf4_proj_dev.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vivado-ip [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vga_fifo/vga_fifo.xci
set_property used_in_implementation false [get_files -all /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vga_fifo/vga_fifo.dcp]
set_property used_in_implementation false [get_files -all /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vga_fifo/vga_fifo/vga_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vga_fifo/vga_fifo/vga_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vga_fifo/vga_fifo_ooc.xdc]
set_property is_locked true [get_files /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vga_fifo/vga_fifo.xci]

read_ip /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/fifo_32x512/fifo_32x512.xci
set_property used_in_implementation false [get_files -all /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/fifo_32x512/fifo_32x512.dcp]
set_property used_in_implementation false [get_files -all /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/fifo_32x512/fifo_32x512/fifo_32x512.xdc]
set_property used_in_implementation false [get_files -all /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/fifo_32x512/fifo_32x512_ooc.xdc]
set_property is_locked true [get_files /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/fifo_32x512/fifo_32x512.xci]

add_files /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vivado_system/vivado_system.bd
set_property used_in_implementation false [get_files -all /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_0/vivado_system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vivado_system/ip/vivado_system_xbar_0/vivado_system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_0/vivado_system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vivado_system/vivado_system_ooc.xdc]
set_property is_locked true [get_files /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/vivado_system/vivado_system.bd]

read_verilog -library xil_defaultlib {
  /home/vytas/INF4/Verilog/init_xillybus/verilog/src/top.v
  /home/vytas/INF4/Verilog/init_xillybus/verilog/src/xillybus.v
  /home/vytas/INF4/Verilog/init_xillybus/verilog/src/xillybus_core.v
  /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/system.v
  /home/vytas/INF4/Verilog/inf4_proj_dev/inf4_proj_dev.srcs/sources_1/new/sw_pe.v
  /home/vytas/INF4/Verilog/inf4_proj_dev/inf4_proj_dev.srcs/sources_1/new/ssd_driver.v
  /home/vytas/INF4/Verilog/inf4_proj_dev/inf4_proj_dev.srcs/sources_1/new/fifo_shift_2x32.v
  /home/vytas/INF4/Verilog/inf4_proj_dev/inf4_proj_dev.srcs/sources_1/new/sw_proc.v
}
set_property edif_extra_search_paths /home/vytas/INF4/Verilog/init_xillybus/cores [current_fileset]
read_xdc /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/xillydemo.xdc
set_property used_in_implementation false [get_files /home/vytas/INF4/Verilog/init_xillybus/vivado-essentials/xillydemo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top top -part xc7z010clg400-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
